---

version: '2'

services:
  zookeeper-1:
    container_name: zookeeper-1
    hostname: zookeeper-1
    image: confluentinc/cp-zookeeper:6.2.6
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-2:
    container_name: zookeeper-2
    hostname: zookeeper-2
    image: confluentinc/cp-zookeeper:6.2.6
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  zookeeper-3:
    container_name: zookeeper-3
    hostname: zookeeper-3
    image: confluentinc/cp-zookeeper:6.2.6
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    network_mode: host
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-1:
    container_name: kafka-1
    hostname: kafka-1
    image: confluentinc/cp-kafka:6.2.6
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_LOG_RETENTION_BYTES: 26214400
      KAFKA_COMPRESSION_TYPE: zstd
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-2:
    container_name: kafka-2
    hostname: kafka-2
    image: confluentinc/cp-kafka:6.2.6
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_LOG_RETENTION_BYTES: 26214400
      KAFKA_COMPRESSION_TYPE: zstd
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
    extra_hosts:
      - "moby:127.0.0.1"

  kafka-3:
    container_name: kafka-3
    hostname: kafka-3
    image: confluentinc/cp-kafka:6.2.6
    network_mode: host
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_LOG_RETENTION_HOURS: 120
      KAFKA_LOG_RETENTION_BYTES: 26214400
      KAFKA_COMPRESSION_TYPE: zstd
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
    extra_hosts:
      - "moby:127.0.0.1"